# Application
spring.application.name=video-frame-extractor
spring.profiles.active=prod

# Kafka Configuration
kafka.enabled=true
#spring.kafka.bootstrap-servers=100.52.199.228:9094
spring.kafka.bootstrap-servers=kafka.video.internal:9092
spring.kafka.consumer.group-id=video-frame-extractor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

# Kafka Topics
kafka.topic.video-uploaded=received-videos
kafka.topic.video-status=process-status-videos

# Kafka Producer
kafka.producer.retries=3
kafka.producer.acks=all

# AWS S3 Configuration
aws.s3.enabled=true
aws.region=${AWS_REGION:us-east-1}
aws.access-key=${AWS_ACCESS_KEY_ID:test}
aws.secret-key=${AWS_SECRET_ACCESS_KEY:test}
aws.s3.bucket-name=postech-fiap-bucket-videos-fase5
aws.s3.videos-prefix=videos/
aws.s3.frames-prefix=frames/
aws.s3.endpoint=${AWS_S3_ENDPOINT:}
aws.s3.path-style-access=false

# FFmpeg Configuration
ffmpeg.path=${FFMPEG_PATH:/usr/bin/ffmpeg}
frame.extraction.output-dir=${FRAME_OUTPUT_DIR:./frames}
frame.extraction.fps=${FRAME_FPS:1}
frame.extraction.max-frames=100

# Server Configuration
server.port=8080

# Logging
logging.level.com.fiap.videoframeextractor=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.com.amazonaws=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
