apiVersion: v1
kind: ConfigMap
metadata:
  name: video-frame-extractor-config
data:
  spring.profiles.active: "prod"
  kafka.bootstrap-servers: "10.0.14.140:9092"
  kafka.enabled: "true"
  app.aws.s3.enabled: "true"
  app.aws.s3.bucket-name: "postech-fiap-bucket-videos-fase5"
  app.aws.s3.videos-prefix: "videos/"
  app.aws.s3.frames-prefix: "frames/"
  app.aws.region: "us-east-1"
